### ISSUE TITLE
Assertion failure in beautify test case

### ISSUE THREAD

**Issue by AidanDelaney** [mjwybrow/adaptagrams#10]
I've compiled adaptagrams with CXXFLAGS="-O0 -g" and with the default CXXFLAGS.  In both cases I get the following failure in the beautify test case.  This backtrace has been generated -O0.  Running on Linux on x86_64.  This failure happens on every run of beautify.

random seed=1207906420
DAG depth=6
maxbranch=4
extraedgeprob0.002000
V=201
E=243
stress=3070.47 iteration=0
stress=2361.57 iteration=1
stress=2050.17 iteration=2
stress=1895.06 iteration=3
stress=1794.66 iteration=4
stress=1732.67 iteration=5
stress=1696.61 iteration=6
stress=1666.28 iteration=7
stress=1643.41 iteration=8
stress=1622.09 iteration=9
stress=1602.09 iteration=10
stress=1575.2 iteration=11
stress=1588.93 iteration=12
unconstrained layout ran in 1.45957 seconds
Removing overlaps...
done.
Running libavoid to compute routes...
WARNING: cola::OutputFile::generate(): No SVG file produced.
         You must have cairomm (and cairo with SVG support) this to work.
done. Libavoid ran in 4.78719 seconds
makefeasible ran in 4.79767 seconds
WARNING: cola::OutputFile::generate(): No SVG file produced.
         You must have cairomm (and cairo with SVG support) this to work.
lt-beautify: ../libtopology/topology_graph.h:325: double topology::Segment::intersection(vpsc::Dim, double, const topology::EdgePoint_, const topology::EdgePoint_, double&) const: Assertion `denom!=0' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6621c39 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.18-12.fc20.x86_64 libgcc-4.8.3-1.fc20.x86_64 libstdc++-4.8.3-1.fc20.x86_64
(gdb) backtrace
#0  0x00007ffff6621c39 in raise () from /lib64/libc.so.6
#1  0x00007ffff6623348 in abort () from /lib64/libc.so.6
#2  0x00007ffff661ab96 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff661ac42 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff7b95cd6 in topology::Segment::intersection (this=0x6ff030, scanDim=vpsc::HORIZONTAL, pos=336.04288043322771, s=0x6ff420, e=0x6ff690, p=@0x7fffffffbda8: 1)

```
at ../libtopology/topology_graph.h:325
```
#5  0x00007ffff7b95b8b in topology::Segment::reverseIntersection (this=0x6ff030, scanDim=vpsc::HORIZONTAL, pos=336.04288043322771, p=@0x7fffffffbda8: 1)

```
at ../libtopology/topology_graph.h:311
```
#6  0x00007ffff7b9419b in topology::BendConstraint::BendConstraint (this=0xa6a340, v=0x6ff690, dim=vpsc::HORIZONTAL) at topology_constraints_constructor.cpp:485
#7  0x00007ffff7b83220 in topology::EdgePoint::createBendConstraint (this=0x6ff690, scanDim=vpsc::HORIZONTAL) at topology_graph.cpp:129
#8  0x00007ffff7b8309e in topology::EdgePoint::prune (this=0x6ffb30, scanDim=vpsc::HORIZONTAL) at topology_graph.cpp:109
#9  0x00007ffff7b94d70 in topology::TopologyConstraints::TopologyConstraints (this=0x7fffffffcd20, axisDim=vpsc::HORIZONTAL,

```
nodes=std::vector of length 201, capacity 201 = {...}, edges=std::vector of length 243, capacity 243 = {...}, clusterHierarchy=0x0, 
vs=std::vector of length 201, capacity 201 = {...}, cs=std::vector of length 0, capacity 0) at topology_constraints_constructor.cpp:698
```
#10 0x00007ffff7ba4f62 in topology::ColaTopologyAddon::moveTo (this=0x6e6770, dim=vpsc::HORIZONTAL, vs=std::vector of length 201, capacity 201 = {...},

```
cs=std::vector of length 0, capacity 0, coords=..., clusterHierarchy=0x0) at cola_topology_addon.cpp:376
```
#11 0x00007ffff74ccc03 in cola::ConstrainedFDLayout::moveTo (this=0x7fffffffdc00, dim=vpsc::HORIZONTAL, target=...) at colafd.cpp:957
#12 0x00007ffff74c88a1 in cola::ConstrainedFDLayout::setPosition (this=0x7fffffffdc00, pos=...) at colafd.cpp:210
#13 0x00007ffff74c88f3 in cola::ConstrainedFDLayout::computeDescentVectorOnBothAxes (this=0x7fffffffdc00, xAxis=true, yAxis=true, stress=1.7976931348623157e+308, x0=...,

```
x1=...) at colafd.cpp:221
```
#14 0x00007ffff74c8d50 in cola::ConstrainedFDLayout::run (this=0x7fffffffdc00, xAxis=true, yAxis=true) at colafd.cpp:270
#15 0x0000000000415bd6 in main () at beautify.cpp:354

**Comment by skieffer** [comment]
Solved by #57.
