### ISSUE TITLE
Test fail: beautify

### ISSUE THREAD

**Issue by mclegrand** [mjwybrow/adaptagrams#28]
Trying to compile adaptagrams, I hit the following issue:

> ~/adaptagrams/cola$ ./libtopology/tests/beautify 
random seed=1207906420
DAG depth=6
maxbranch=4
extraedgeprob0.002000
V=201
E=243
stress=3070.47 iteration=0
stress=2361.57 iteration=1
stress=2050.17 iteration=2
stress=1895.06 iteration=3
stress=1794.66 iteration=4
stress=1732.67 iteration=5
stress=1696.61 iteration=6
stress=1666.28 iteration=7
stress=1643.41 iteration=8
stress=1622.09 iteration=9
stress=1602.09 iteration=10
stress=1575.2 iteration=11
stress=1588.93 iteration=12
unconstrained layout ran in 0.33662 seconds
Removing overlaps...
done.
Running libavoid to compute routes...
writing svg file: beautify0.svg
Wrote file "beautify0.svg"
done. Libavoid ran in 1.09424 seconds
makefeasible ran in 1.09703 seconds
writing svg file: beautify1.svg
Wrote file "beautify1.svg"
beautify: ../libtopology/topology_graph.h:325: double topology::Segment::intersection(vpsc::Dim, double, const topology::EdgePoint*, const topology::EdgePoint*, double&) const: Assertion `denom!=0' failed.
Aborted

**Comment by skieffer** [comment]
Solved by #57.
